import { Injectable, OnModuleDestroy, ServiceUnavailableException, UnauthorizedException } from '@nestjs/common';
import { Queue } from 'bullmq';
import Redis from 'ioredis';
import { createOpaqueToken, hashPassword, hashToken, verifyPassword } from '@havona/auth';
import { PrismaService } from '../common/prisma.service';
import { AuditService, AuditContext } from '../audit/audit.service';
const MAX_ATTEMPTS=5, LOCK_MINUTES=15, SESSION_HOURS=12;
const includeAccess={roles:{include:{role:{include:{permissions:{include:{permission:true}}}}}}} as const;
@Injectable() export class AuthService implements OnModuleDestroy {
 private readonly redis=new Redis(process.env.REDIS_URL??'redis://localhost:6379',{maxRetriesPerRequest:null,lazyConnect:true});
 private readonly emailQueue=new Queue('email',{connection:this.redis});
 constructor(private readonly db:PrismaService,private readonly audit:AuditService){}
 async onModuleDestroy(){await this.emailQueue.close();this.redis.disconnect()}
 private principal(user:any){return {id:user.id,email:user.email,name:user.name,isActive:user.isActive,roles:user.roles.map((x:any)=>x.role.name),permissions:[...new Set<string>(user.roles.flatMap((x:any)=>x.role.permissions.map((p:any)=>p.permission.key)))]};}
 async login(email:string,password:string,context:AuditContext){const user=await this.db.user.findUnique({where:{email},include:includeAccess});const now=new Date();if(!user){await hashPassword(password);await this.audit.record('AUTH_LOGIN_FAILED','Authentication',undefined,context,{reason:'INVALID_CREDENTIALS'});throw new UnauthorizedException('Credenciales inválidas');}if(!user.isActive||user.lockedUntil&&user.lockedUntil>now||!await verifyPassword(user.passwordHash,password)){const attempts=user.failedLoginAttempts+1;await this.db.user.update({where:{id:user.id},data:{failedLoginAttempts:attempts,lockedUntil:attempts>=MAX_ATTEMPTS?new Date(Date.now()+LOCK_MINUTES*60000):undefined}});await this.audit.record('AUTH_LOGIN_FAILED','User',user.id,context,{reason:user.isActive?'INVALID_CREDENTIALS':'INACTIVE'});throw new UnauthorizedException('Credenciales inválidas');}const token=createOpaqueToken(),csrf=createOpaqueToken();await this.db.$transaction(async tx=>{await tx.user.update({where:{id:user.id},data:{failedLoginAttempts:0,lockedUntil:null,lastLoginAt:now}});await tx.session.create({data:{tokenHash:hashToken(token),csrfHash:hashToken(csrf),userId:user.id,expiresAt:new Date(Date.now()+SESSION_HOURS*3600000),ipAddress:context.ipAddress,userAgent:context.userAgent}});await tx.auditLog.create({data:{action:'AUTH_LOGIN_SUCCESS',resource:'User',resourceId:user.id,actorUserId:user.id,ipAddress:context.ipAddress,userAgent:context.userAgent}})});return {token,csrf,user:this.principal(user)};}
 async authenticate(token?:string){if(!token)return null;const session=await this.db.session.findUnique({where:{tokenHash:hashToken(token)},include:{user:{include:includeAccess}}});if(!session||session.revokedAt||session.expiresAt<=new Date()||!session.user.isActive)return null;return {sessionId:session.id,csrfHash:session.csrfHash,user:this.principal(session.user)};}
 async logout(sessionId:string,userId:string,context:AuditContext){await this.db.$transaction(async tx=>{await tx.session.updateMany({where:{id:sessionId,revokedAt:null},data:{revokedAt:new Date()}});await tx.auditLog.create({data:{action:'AUTH_LOGOUT',resource:'Session',resourceId:sessionId,actorUserId:userId,ipAddress:context.ipAddress,userAgent:context.userAgent}})});}
 async forgotPassword(email:string,context:AuditContext){const user=await this.db.user.findUnique({where:{email}});if(!user||!user.isActive)return {};const token=createOpaqueToken(48);const record=await this.db.$transaction(async tx=>{await tx.passwordResetToken.updateMany({where:{userId:user.id,usedAt:null},data:{usedAt:new Date()}});const created=await tx.passwordResetToken.create({data:{userId:user.id,tokenHash:hashToken(token),expiresAt:new Date(Date.now()+30*60000)}});await tx.auditLog.create({data:{action:'AUTH_PASSWORD_RESET_REQUESTED',resource:'User',resourceId:user.id,actorUserId:user.id,ipAddress:context.ipAddress,userAgent:context.userAgent}});return created;});try{const origin=process.env.APP_ORIGIN??'http://localhost:3000';await this.emailQueue.add('password-reset',{to:user.email,resetUrl:`${origin}/restablecer-contrasena?token=${encodeURIComponent(token)}`},{attempts:5,backoff:{type:'exponential',delay:5000},removeOnComplete:100,removeOnFail:500});}catch{await this.db.passwordResetToken.deleteMany({where:{id:record.id}});await this.audit.record('AUTH_PASSWORD_RESET_DELIVERY_FAILED','User',user.id,context,{reason:'QUEUE_UNAVAILABLE'});if(process.env.NODE_ENV==='production')throw new ServiceUnavailableException('No fue posible procesar la recuperación');return {developmentResetToken:token};}return process.env.NODE_ENV==='production'?{}:{developmentResetToken:token};}
 async resetPassword(token:string,password:string,context:AuditContext){const record=await this.db.passwordResetToken.findUnique({where:{tokenHash:hashToken(token)}});if(!record||record.usedAt||record.expiresAt<=new Date())throw new UnauthorizedException('Token inválido o vencido');const passwordHash=await hashPassword(password);await this.db.$transaction(async tx=>{await tx.user.update({where:{id:record.userId},data:{passwordHash,failedLoginAttempts:0,lockedUntil:null}});await tx.passwordResetToken.update({where:{id:record.id},data:{usedAt:new Date()}});await tx.session.updateMany({where:{userId:record.userId,revokedAt:null},data:{revokedAt:new Date()}});await tx.auditLog.create({data:{action:'AUTH_PASSWORD_RESET_COMPLETED',resource:'User',resourceId:record.userId,actorUserId:record.userId,ipAddress:context.ipAddress,userAgent:context.userAgent}})});}
}
