'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Alert, EmptyState, Skeleton } from '@havona/ui';
import { AlertTriangle, ArrowRight, BarChart3, Database, Download, Target } from 'lucide-react';
import { PageHeader } from '@/components/page';
import { analyticsApi, AnalyticsSummary } from '@/lib/analytics';
import { formatMoney } from '@/lib/crm';
import { API_URL, messageOf } from '@/lib/api';
import { useAuth } from '@/lib/auth';

const labels: Record<string, string> = { 'crm.prospects.created': 'Prospectos', 'crm.opportunities.created': 'Oportunidades', 'calendar.appointments_scheduled': 'Citas', 'crm.opportunities.won': 'Cierres ganados', 'sales.win_rate': 'Conversión', 'sales.pipeline_value': 'Pipeline monetario' };
const format = (metric: AnalyticsSummary['metrics'][number]['current']) => metric.money?.length ? metric.money.map((item) => formatMoney(item.amount, item.currency)).join(' · ') : metric.value === null ? 'No disponible' : metric.metric.includes('rate') ? `${(metric.value * 100).toFixed(1)}%` : new Intl.NumberFormat('es-CO', { maximumFractionDigits: 1 }).format(metric.value);

export default function AnalyticsPage() {
  const { can, user } = useAuth();
  const [preset, setPreset] = useState('month');
  const [summary, setSummary] = useState<AnalyticsSummary | null>(null);
  const [team, setTeam] = useState<Awaited<ReturnType<typeof analyticsApi.team>>>([]);
  const [quality, setQuality] = useState<Awaited<ReturnType<typeof analyticsApi.quality>> | null>(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setError(''); const [next, qualityResult, teamResult] = await Promise.all([analyticsApi.summary({ preset }), analyticsApi.quality({ preset }), can('analytics.read_team') ? analyticsApi.team({ preset }) : Promise.resolve([])]); setSummary(next); setQuality(qualityResult); setTeam(teamResult); } catch (reason) { setError(messageOf(reason)); } finally { setLoading(false); } }, [preset, can]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <><PageHeader title="Inteligencia comercial" description="Calculando evidencia desde los dominios operativos autorizados." /><Skeleton className="h-[680px]" /></>;
  if (!summary) return <><PageHeader title="Inteligencia comercial" description="Command Center de HAVONA CAPITAL GROUP." />{error ? <Alert>{error}</Alert> : <EmptyState title="Sin analítica disponible" description="No fue posible construir el resumen autorizado." />}</>;
  return <div className="space-y-10">
    <PageHeader title={can('analytics.read_team') ? 'Command Center comercial' : 'Mi negocio'} description="Hechos, riesgos y prioridades con definiciones reproducibles y ámbito RBAC." />
    {error && <Alert>{error}</Alert>}
    <section className="flex flex-col justify-between gap-4 border-y border-slate-200 py-4 md:flex-row md:items-center" aria-label="Controles analíticos">
      <div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand-700">{summary.freshness.status} · {summary.period.timezone}</p><p className="mt-1 text-sm text-slate-500">Actualizado {new Date(summary.freshness.generatedAt).toLocaleString('es-CO')}</p></div>
      <div className="flex flex-wrap gap-2"><label className="sr-only" htmlFor="analytics-period">Periodo</label><select id="analytics-period" value={preset} onChange={(event) => setPreset(event.target.value)} className="rounded-full border border-slate-300 bg-white px-4 py-2 text-sm"><option value="today">Hoy</option><option value="week">Semana</option><option value="month">Mes</option><option value="quarter">Trimestre</option><option value="year">Año</option></select>{can('analytics.export') && <a href={`${API_URL}/analytics/exports/priorities.csv?preset=${preset}`} className="rounded-full border border-brand-200 px-4 py-2 text-sm font-semibold text-brand-800"><Download className="mr-2 inline size-4" />Exportar prioridades</a>}</div>
    </section>
    <section className="grid gap-x-8 gap-y-7 md:grid-cols-2 xl:grid-cols-3" aria-label="Indicadores ejecutivos">{summary.metrics.map(({ current, delta }) => <article key={current.metric} className="border-l-2 border-brand-200 pl-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">{labels[current.metric] ?? current.metric}</p><p className="mt-2 font-display text-4xl text-brand-950">{format(current)}</p><p className={`mt-2 text-sm ${delta.absolute !== null && delta.absolute < 0 ? 'text-red-700' : 'text-slate-500'}`}>{delta.status === 'COMPARABLE' ? `${delta.absolute! >= 0 ? '+' : ''}${delta.absolute?.toFixed(1)} vs. periodo anterior` : current.coverage.warning ?? 'Sin periodo comparable'}</p></article>)}</section>
    <section className="grid gap-6 rounded-[28px] border border-brand-100 bg-brand-50/60 p-6 md:grid-cols-3" aria-label="Pipeline financiero">
      <div><p className="text-xs font-semibold uppercase tracking-wider text-brand-700">Pipeline activo</p><div className="mt-2 space-y-1 font-display text-2xl text-brand-950">{summary.pipeline.monetaryValue.values?.length ? summary.pipeline.monetaryValue.values.map((item) => <p key={item.currency}>{formatMoney(item.amount, item.currency)}</p>) : <p>No disponible</p>}</div><p className="mt-2 text-xs text-slate-600">Cobertura {summary.pipeline.monetaryValue.coverage.percentage ?? '—'}%</p></div>
      <div><p className="text-xs font-semibold uppercase tracking-wider text-brand-700">Pipeline ponderado</p><div className="mt-2 space-y-1 font-display text-2xl text-brand-950">{summary.pipeline.weightedPipeline?.values.length ? summary.pipeline.weightedPipeline.values.map((item) => <p key={item.currency}>{formatMoney(item.amount, item.currency)}</p>) : <p>No disponible</p>}</div><p className="mt-2 text-xs text-slate-600">Solo montos con probabilidad explícita.</p></div>
      <div><p className="text-xs font-semibold uppercase tracking-wider text-brand-700">Forecast conservador</p><div className="mt-2 space-y-2 text-sm">{summary.pipeline.forecast?.categories.map((group) => <div key={group.category}><strong>{group.category}</strong><span className="ml-2 text-slate-600">{group.values.length ? group.values.map((item) => formatMoney(item.amount, item.currency)).join(' · ') : 'Sin datos'}</span></div>)}</div><p className="mt-2 text-xs text-slate-600">Categoría declarada; no garantiza cierre.</p></div>
    </section>
    <div className="grid gap-8 xl:grid-cols-[1.35fr_.65fr]">
      <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white"><header className="flex items-center justify-between border-b p-6"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand-600">Embudo real</p><h2 className="mt-1 font-display text-2xl">Movimiento por etapa</h2></div><BarChart3 className="text-brand-500" /></header><div className="divide-y">{summary.funnel.stages.map((row, index) => <div key={row.stage.key} className="grid grid-cols-[32px_1fr_auto] items-center gap-4 p-4 sm:px-6"><span className="font-display text-sm text-slate-400">{String(index + 1).padStart(2, '0')}</span><div><p className="font-semibold text-slate-900">{row.stage.name}</p><p className="text-xs text-slate-500">Mediana {row.medianDays === null ? 'sin muestra' : `${row.medianDays.toFixed(1)} días`}</p></div><div className="text-right"><p className="font-display text-2xl text-brand-800">{row.entered}</p><p className="text-xs text-slate-500">{row.conversionToNext === null ? '—' : `${(row.conversionToNext * 100).toFixed(0)}% avanza`}</p></div></div>)}</div></section>
      <section><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand-600">Prioridades de hoy</p><h2 className="mt-2 font-display text-3xl">Lo que requiere decisión</h2><div className="mt-5 divide-y border-y">{summary.priorities.length ? summary.priorities.map((item) => <Link key={`${item.type}-${item.entityId}`} href={item.entityType === 'Opportunity' ? '/crm/pipeline' : '/crm/tareas'} className="group block py-5"><span className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-amber-700"><AlertTriangle className="size-4" />{item.severity}</span><p className="mt-2 font-semibold text-slate-950">{item.title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{item.reason}</p><span className="mt-2 inline-flex items-center text-sm font-semibold text-brand-700">Investigar <ArrowRight className="ml-1 size-4 transition group-hover:translate-x-1" /></span></Link>) : <EmptyState title="Sin prioridades críticas" description="No existen señales accionables en su ámbito actual." />}</div></section>
    </div>
    {team.length > 0 && <section><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand-600">Equipo autorizado</p><h2 className="mt-2 font-display text-3xl">Ejecución comercial</h2></div><Target className="text-brand-500" /></div><div className="overflow-x-auto rounded-[24px] border bg-white"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b bg-brand-50/70 text-xs uppercase tracking-wider text-slate-600"><tr><th className="p-4">Consultor</th><th>Prospectos</th><th>Oportunidades</th><th>Vencidas</th><th>Win rate</th></tr></thead><tbody className="divide-y">{team.map((row) => <tr key={row.user.id}><td className="p-4 font-semibold">{row.user.name}{row.user.id === user?.id && <span className="ml-2 text-xs text-brand-600">Usted</span>}</td><td>{row.prospects}</td><td>{row.opportunities}</td><td className={row.overdueTasks ? 'font-semibold text-red-700' : ''}>{row.overdueTasks}</td><td>{row.winRate === null ? 'Sin muestra' : `${(row.winRate * 100).toFixed(1)}%`}</td></tr>)}</tbody></table></div></section>}
    <section className="grid gap-6 md:grid-cols-2"><div className="rounded-[24px] bg-brand-950 p-7 text-white"><Database className="size-5 text-blue-300" /><h2 className="mt-5 font-display text-2xl">Calidad de evidencia</h2><p className="mt-2 text-blue-100">{quality?.summary.status ?? summary.dataQuality.status} · {quality?.summary.issues ?? summary.dataQuality.issues} observaciones incompletas.</p><div className="mt-5 space-y-3">{quality?.checks.slice(0, 4).map((check) => <div key={check.key} className="flex justify-between border-t border-white/15 pt-3 text-sm"><span>{check.key}</span><span>{check.coveragePercentage === null ? 'Sin muestra' : `${check.coveragePercentage}%`}</span></div>)}</div></div><div className="rounded-[24px] border border-brand-100 bg-brand-50 p-7"><Target className="size-5 text-brand-700" /><h2 className="mt-5 font-display text-2xl text-brand-950">Objetivos</h2>{summary.goals.length ? <div className="mt-4 space-y-3">{summary.goals.map((goal) => <div key={goal.id} className="border-t border-brand-200 pt-3"><p className="font-semibold">{labels[goal.metricKey] ?? goal.metricKey}</p><p className="text-sm text-slate-600">Meta {goal.targetValue} · vence {new Date(goal.periodEnd).toLocaleDateString('es-CO')}</p></div>)}</div> : <p className="mt-2 text-slate-600">No hay metas activas asignadas a este ámbito. No se muestran avances artificiales.</p>}</div></section>
  </div>;
}
