import type {Metadata} from 'next';
import Link from 'next/link';
import {ArrowLeft,CheckCircle2} from 'lucide-react';
import {notFound} from 'next/navigation';
import {LeadForm} from '@/components/public/lead-form';
import {PublicFooter} from '@/components/public/public-footer';
import {PublicHeader} from '@/components/public/public-header';
import {Reveal} from '@/components/public/reveal';
import {publicPageMap,publicPages} from '@/lib/public-pages';

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return publicPages.map(({slug})=>({slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const page=publicPageMap.get(slug);if(!page)return{};return{title:page.shortTitle,description:page.description,alternates:{canonical:`/${slug}`},openGraph:{title:`${page.shortTitle} | HAVONA CAPITAL`,description:page.description,url:`/${slug}`},twitter:{title:`${page.shortTitle} | HAVONA CAPITAL`,description:page.description}}}
export default async function LandingPage({params}:Props){const{slug}=await params;const page=publicPageMap.get(slug);if(!page)notFound();return <div className="public-page"><PublicHeader/><main><section className="relative overflow-hidden pb-20 pt-36 sm:pt-44"><div className="public-orb -right-32 top-20 size-[32rem] bg-blue-200/50"/><div className="public-container"><Reveal><Link href="/#soluciones" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><ArrowLeft className="size-4"/>Todas las soluciones</Link><p className="eyebrow mt-10">{page.eyebrow}</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-semibold leading-[1.04] tracking-[-.04em] text-brand-800 sm:text-6xl">{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">{page.description}</p><Link href="#consultoria" className="button-primary mt-8">Solicitar consultoría</Link></Reveal></div></section><section className="bg-white py-20"><div className="public-container grid gap-5 md:grid-cols-3"><InfoBlock index="01" title="El desafío" text={page.problem}/><InfoBlock index="02" title="El contexto" text={page.context}/><InfoBlock index="03" title="Cómo ayudamos" text={page.solution}/></div></section>{slug==='empresarios'&&<section className="bg-white pb-20"><div className="public-container grid gap-5 md:grid-cols-2"><article id="hombre-clave" className="scroll-mt-32 rounded-[1.5rem] bg-brand-50 p-7"><h2 className="font-display text-2xl font-semibold text-brand-800">Hombre clave</h2><p className="mt-3 leading-7 text-slate-600">Explore cómo la dependencia de una persona esencial puede afectar la continuidad y qué contexto necesita revisar con un consultor.</p></article><article id="beneficios-empleados" className="scroll-mt-32 rounded-[1.5rem] bg-brand-50 p-7"><h2 className="font-display text-2xl font-semibold text-brand-800">Beneficios para empleados</h2><p className="mt-3 leading-7 text-slate-600">Inicie una conversación sobre objetivos, equipo y criterios para estructurar una estrategia de beneficios coherente.</p></article></div></section>}<section className="py-24"><div className="public-container grid gap-12 lg:grid-cols-[.78fr_1.22fr]"><Reveal><p className="eyebrow">Una conversación útil desde el inicio</p><h2 className="section-title mt-4">Un siguiente paso claro y responsable.</h2><ul className="mt-8 grid gap-5">{page.benefits.map(item=><li key={item} className="flex gap-3 leading-7 text-slate-700"><CheckCircle2 className="mt-1 size-5 shrink-0 text-brand-500"/>{item}</li>)}</ul></Reveal><Reveal delay={.1}><LeadForm landing={page.slug} interest={page.interest} compact/></Reveal></div></section></main><PublicFooter/></div>}
function InfoBlock({index,title,text}:{index:string;title:string;text:string}){return <Reveal><article className="h-full rounded-[1.5rem] border border-slate-200 bg-slate-50/70 p-7"><span className="font-display text-sm font-bold text-brand-500">{index}</span><h2 className="mt-5 font-display text-2xl font-semibold text-brand-800">{title}</h2><p className="mt-4 leading-7 text-slate-600">{text}</p></article></Reveal>}
