'use client';

import {useCallback,useEffect,useState} from 'react';
import {Badge,Button,Card,EmptyState,Field,Modal,SelectField,Skeleton} from '@havona/ui';
import {PageHeader} from '@/components/page';
import {api,messageOf} from '@/lib/api';
import type {ApiList,Prospect} from '@/lib/types';

const dateTime=(value:string)=>new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
const labels:Record<string,string>={NEW:'Nuevo',REVIEWED:'Revisado',ARCHIVED:'Archivado',CAPTURED:'Captado',RECAPTURED:'Nueva captura'};

export default function ProspectsPage(){
 const[items,setItems]=useState<Prospect[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[source,setSource]=useState('');const[interest,setInterest]=useState('');const[sortBy,setSortBy]=useState('createdAt');const[sortOrder,setSortOrder]=useState('desc');const[selected,setSelected]=useState<Prospect|null>();const[detailLoading,setDetailLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams({page:'1',pageSize:'100',sortBy,sortOrder});if(search.trim())params.set('search',search.trim());if(status)params.set('status',status);if(source)params.set('source',source);if(interest)params.set('interest',interest);const response=await api<ApiList<Prospect>>(`/prospects?${params}`);setItems(response.data)}catch(reason){setError(messageOf(reason))}finally{setLoading(false)}},[search,status,source,interest,sortBy,sortOrder]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer)},[load]);
 async function open(id:string){setDetailLoading(true);setError('');try{setSelected(await api<Prospect>(`/prospects/${id}`))}catch(reason){setError(messageOf(reason))}finally{setDetailLoading(false)}}
 return <><PageHeader title="Prospectos" description="Capturas iniciales con fuente, interés y evidencia de consentimiento."/>
  <Card className="mb-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-6"><div className="xl:col-span-2"><Field label="Buscar" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Nombre, correo, teléfono o ciudad"/></div><SelectField label="Estado" value={status} onChange={event=>setStatus(event.target.value)}><option value="">Todos</option><option value="NEW">Nuevos</option><option value="REVIEWED">Revisados</option><option value="ARCHIVED">Archivados</option></SelectField><SelectField label="Fuente" value={source} onChange={event=>setSource(event.target.value)}><option value="">Todas</option><option value="direct">Directo</option><option value="organic">Orgánico</option><option value="campaign">Campaña</option><option value="referral">Referido</option><option value="henry-entry">Entrada Henry</option></SelectField><SelectField label="Interés" value={interest} onChange={event=>setInterest(event.target.value)}><option value="">Todos</option><option value="pension">Pensión</option><option value="educacion">Educación</option><option value="patrimonio">Patrimonio</option><option value="proteccion">Protección</option><option value="accidentes">Accidentes</option><option value="empresarios">Empresarios</option><option value="socios">Socios</option><option value="socio-unico">Socio único</option><option value="consultores">Consultores</option><option value="consultoria">Consultoría general</option></SelectField><div className="grid grid-cols-2 gap-2"><SelectField label="Orden" value={sortBy} onChange={event=>setSortBy(event.target.value)}><option value="createdAt">Captura</option><option value="lastCapturedAt">Interacción</option><option value="name">Nombre</option><option value="status">Estado</option></SelectField><SelectField label="Dirección" value={sortOrder} onChange={event=>setSortOrder(event.target.value)}><option value="desc">Desc.</option><option value="asc">Asc.</option></SelectField></div></div></Card>
  {error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}</p>}
  <Card className="overflow-x-auto p-0">{loading?<Skeleton className="m-5 h-60"/>:items.length===0?<EmptyState title="Sin resultados" description="No hay prospectos que coincidan con los filtros actuales."/>:<table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Prospecto</th><th className="p-4">Interés</th><th className="p-4">Fuente</th><th className="p-4">Consentimiento</th><th className="p-4">Última captura</th><th className="p-4">Estado</th><th className="p-4 text-right">Acción</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-b last:border-0"><td className="p-4"><strong className="block text-slate-900">{item.name}</strong><span className="text-slate-500">{item.email||item.phone||'Sin contacto visible'}</span></td><td className="p-4 capitalize">{item.interest.replaceAll('-',' ')}</td><td className="p-4"><span className="block">{item.source.name}</span><span className="text-xs text-slate-500">{item.landing}</span></td><td className="p-4"><Badge tone={item._count?.consents?'success':'danger'}>{item._count?.consents?'Registrado':'No disponible'}</Badge></td><td className="p-4 text-slate-500">{dateTime(item.lastCapturedAt)}</td><td className="p-4"><Badge>{labels[item.status]??item.status}</Badge></td><td className="p-4 text-right"><Button className="bg-slate-100 text-slate-800 hover:bg-slate-200" busy={detailLoading} onClick={()=>void open(item.id)}>Ver detalle</Button></td></tr>)}</tbody></table>}</Card>
  <Modal open={selected!==undefined&&selected!==null} title="Detalle del prospecto" onClose={()=>setSelected(undefined)}>{selected&&<div className="grid gap-6"><section className="grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><Detail label="Nombre" value={selected.name}/><Detail label="Ciudad" value={selected.city}/><Detail label="Correo" value={selected.email||'No suministrado'}/><Detail label="Teléfono" value={selected.phone||'No suministrado'}/><Detail label="Interés" value={selected.interest}/><Detail label="Fuente" value={`${selected.source.name} · ${selected.landing}`}/>{selected.message&&<div className="sm:col-span-2"><Detail label="Mensaje" value={selected.message}/></div>}</section><section><h3 className="font-display text-lg font-semibold text-brand-800">Consentimiento</h3><div className="mt-3 grid gap-2">{selected.consents?.map(consent=><div key={consent.id} className="rounded-xl border p-3 text-sm"><strong>{consent.accepted?'Aceptado':'No aceptado'}</strong><span className="ml-2 text-slate-500">Política {consent.privacyVersion} · {dateTime(consent.acceptedAt)}</span></div>)}</div></section><section><h3 className="font-display text-lg font-semibold text-brand-800">Historial inicial</h3><ol className="mt-3 grid gap-2">{selected.events?.map(event=><li key={event.id} className="rounded-xl border p-3 text-sm"><strong>{labels[event.type]??event.type}</strong><span className="ml-2 text-slate-500">{event.landing} · {dateTime(event.createdAt)}</span></li>)}</ol></section></div>}</Modal>
 </>}

function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm text-slate-900">{value}</dd></div>}
