'use client';
import Link from 'next/link';
import {AnimatePresence,motion,useReducedMotion,useScroll,useSpring} from 'motion/react';
import {ArrowRight,ArrowUpRight,Building2,Check,Shield,UsersRound} from 'lucide-react';
import {useRef,useState} from 'react';
import {Reveal} from './reveal';

const people=[
 {key:'proteccion',index:'01',label:'Protección',href:'/proteccion',title:'Preservar la estabilidad de quienes importan.',text:'Ordenamos las decisiones que ayudan a proteger la continuidad familiar frente a escenarios imprevistos.',visual:'continuidad'},
 {key:'pension',index:'02',label:'Pensión',href:'/pension',title:'Dar estructura al futuro que quiere vivir.',text:'Construimos una conversación de retiro que parte de su contexto, sus prioridades y el horizonte que desea proyectar.',visual:'horizonte'},
 {key:'educacion',index:'03',label:'Educación',href:'/educacion',title:'Acompañar proyectos que transforman generaciones.',text:'Integramos la educación dentro de una visión patrimonial que conecta oportunidades presentes y proyectos familiares.',visual:'propósito'},
 {key:'patrimonio',index:'04',label:'Patrimonio',href:'/patrimonio',title:'Convertir objetivos dispersos en una dirección.',text:'Conectamos sus metas de largo plazo con decisiones patrimoniales estructuradas y acompañamiento consultivo.',visual:'estructura'},
 {key:'accidentes',index:'05',label:'Accidentes',href:'/accidentes',title:'Prepararse sin vivir desde la incertidumbre.',text:'Evaluamos cómo cuidar la estabilidad personal y familiar frente a eventos que alteran el curso cotidiano.',visual:'resiliencia'},
];
const companies=[
 {href:'/empresarios',number:'01',title:'Protección empresarial',detail:'Continuidad y estructura frente a riesgos que pueden alterar la operación.'},
 {href:'/socios',number:'02',title:'Socios',detail:'Conversaciones y mecanismos para proteger la estructura societaria.'},
 {href:'/socio-unico',number:'03',title:'Socio único',detail:'Continuidad cuando conocimiento y dirección se concentran en una persona.'},
 {href:'/empresarios#hombre-clave',number:'04',title:'Hombre clave',detail:'Lectura de dependencias esenciales dentro de la organización.'},
 {href:'/empresarios#beneficios-empleados',number:'05',title:'Beneficios',detail:'Estrategias coherentes con el equipo y el propósito empresarial.'},
];
const path=[{verb:'Proteger',text:'Reconocer lo esencial y reducir la exposición ante lo inesperado.'},{verb:'Estructurar',text:'Dar orden a prioridades, decisiones y horizontes patrimoniales.'},{verb:'Construir',text:'Conectar acciones presentes con objetivos que requieren continuidad.'},{verb:'Proyectar',text:'Mantener una visión de futuro con acompañamiento y capacidad de adaptación.'}];
const process=[{number:'01',title:'Comprendemos su contexto.',text:'Escuchamos antes de proponer. Su realidad personal, familiar o empresarial define el punto de partida.'},{number:'02',title:'Identificamos prioridades.',text:'Diferenciamos lo urgente de lo importante para enfocar la conversación donde genera mayor claridad.'},{number:'03',title:'Diseñamos una estrategia.',text:'Articulamos protección, patrimonio y horizonte dentro de una ruta comprensible y coherente.'},{number:'04',title:'Lo acompañamos en el tiempo.',text:'Las decisiones evolucionan. El acompañamiento permite revisarlas con contexto y trazabilidad.'}];

export function HomeNarrative(){return <><Manifesto/><PeopleExplorer/><EnterpriseExperience/><PatrimonialPath/><ConsultativeProcess/><TrustStatement/><ClosingStatement/></>}
function Manifesto(){return <section className="home-manifesto" aria-labelledby="manifesto-title"><div className="public-container manifesto-grid"><Reveal><p className="narrative-index">02 — Nuestra convicción</p></Reveal><Reveal className="manifesto-copy"><h2 id="manifesto-title"><span>El patrimonio</span><strong>no se improvisa.</strong></h2><p>Se protege, se estructura y se construye con decisiones que conectan el presente con el futuro.</p></Reveal><div className="manifesto-seal" aria-hidden="true"><span>H</span><i>Visión integral</i></div></div></section>}
function PeopleExplorer(){const[active,setActive]=useState(people[0]);const reduced=useReducedMotion();function move(current:number,key:string){let next=current;if(key==='ArrowRight'||key==='ArrowDown')next=(current+1)%people.length;else if(key==='ArrowLeft'||key==='ArrowUp')next=(current-1+people.length)%people.length;else if(key==='Home')next=0;else if(key==='End')next=people.length-1;else return;setActive(people[next]);requestAnimationFrame(()=>document.getElementById(`people-tab-${people[next].key}`)?.focus())}return <section id="soluciones" className="people-experience scroll-mt-24" aria-labelledby="people-title"><div className="public-container"><div className="experience-heading"><div><p className="narrative-index">03 — Personas y familias</p><h2 id="people-title">Decisiones para cada momento de vida.</h2></div><p>Explore el contexto que más se acerca a la conversación que quiere iniciar.</p></div><div id="personas" className="people-console scroll-mt-28"><div className="people-nav" role="tablist" aria-label="Soluciones para personas y familias">{people.map((item,index)=><button id={`people-tab-${item.key}`} key={item.key} type="button" role="tab" tabIndex={active.key===item.key?0:-1} aria-selected={active.key===item.key} aria-controls="people-panel" onKeyDown={event=>move(index,event.key)} onClick={()=>setActive(item)}><span>{item.index}</span>{item.label}<i/></button>)}</div><div className="people-stage" id="people-panel" role="tabpanel" aria-labelledby={`people-tab-${active.key}`} tabIndex={0}><div className={`people-visual visual-${active.key}`} aria-hidden="true"><span className="visual-word">{active.visual}</span><div className="visual-core"><i/><i/><i/></div></div><AnimatePresence mode="wait" initial={false}><motion.div key={active.key} className="people-content" initial={reduced?{opacity:0}:{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.35}}><p>{active.index} / 05</p><h3>{active.title}</h3><span>{active.text}</span><Link href={active.href}>Explorar esta solución <ArrowUpRight/></Link></motion.div></AnimatePresence></div></div></div></section>}
function EnterpriseExperience(){return <section id="empresas" className="enterprise-experience scroll-mt-24" aria-labelledby="enterprise-title"><div className="enterprise-lines" aria-hidden="true"/><div className="public-container enterprise-layout"><div className="enterprise-intro"><p className="narrative-index light">04 — Empresas y socios</p><h2 id="enterprise-title">La continuidad también se diseña.</h2><p>Una organización concentra relaciones, conocimiento y decisiones. Proteger su continuidad exige leer el sistema completo.</p><Link href="/empresarios">Conversar sobre mi empresa <ArrowRight/></Link></div><div className="enterprise-list">{companies.map(item=><Link key={item.title} href={item.href}><span>{item.number}</span><div><h3>{item.title}</h3><p>{item.detail}</p></div><ArrowUpRight/></Link>)}</div></div></section>}
function PatrimonialPath(){const section=useRef<HTMLElement>(null);const{scrollYProgress}=useScroll({target:section,offset:['start .75','end .35']});const progress=useSpring(scrollYProgress,{stiffness:70,damping:24});return <section className="patrimonial-path" ref={section} aria-labelledby="path-title"><div className="public-container"><div className="path-heading"><p className="narrative-index">05 — Una visión que evoluciona</p><h2 id="path-title">Del presente<br/>a lo que sigue.</h2></div><div className="path-track"><div className="path-line" aria-hidden="true"><motion.i style={{scaleY:progress}}/></div>{path.map((item,index)=><Reveal key={item.verb} className="path-step" delay={index*.05}><span>0{index+1}</span><h3>{item.verb}</h3><p>{item.text}</p></Reveal>)}</div></div></section>}
function ConsultativeProcess(){return <section className="consultative-process" aria-labelledby="process-title"><div className="public-container"><div className="process-heading"><p className="narrative-index">06 — Método consultivo</p><h2 id="process-title">La claridad se construye en conversación.</h2></div><div className="process-list">{process.map(item=><div key={item.number} className="process-row"><span>{item.number}</span><h3>{item.title}</h3><p>{item.text}</p></div>)}</div></div></section>}
function TrustStatement(){return <section className="trust-statement" aria-labelledby="trust-title"><div className="trust-orbit" aria-hidden="true"><span/><span/><span/></div><div className="public-container trust-inner"><p className="narrative-index">07 — Confianza por diseño</p><div className="trust-words" aria-hidden="true"><span>Confidencialidad</span><span>Metodología</span><span>Trazabilidad</span><span>Tecnología</span></div><h2 id="trust-title">Decisiones importantes merecen<br/><em>criterio, cuidado y continuidad.</em></h2><p>Un enfoque consultivo que combina acompañamiento humano, procesos claros y tecnología aplicada con propósito.</p><div className="trust-principles"><span><Shield/>Control de acceso</span><span><UsersRound/>Acompañamiento</span><span><Building2/>Visión integral</span><span><Check/>Consentimiento</span></div></div></section>}
function ClosingStatement(){return <section className="closing-statement"><div className="public-container closing-inner"><p className="narrative-index">08 — El primer paso</p><h2>Las mejores decisiones patrimoniales comienzan con <span>una conversación.</span></h2><div className="closing-actions"><Link href="#consultoria">Agenda una consultoría <ArrowRight/></Link><Link href="/?experiencia=henry#consultoria">Habla con Henry <ArrowUpRight/></Link></div></div></section>}
