'use client';
import Link from 'next/link';
import {zodResolver} from '@hookform/resolvers/zod';
import {CheckCircle2,LoaderCircle,Send} from 'lucide-react';
import {cloneElement,useEffect,useId,useState} from 'react';
import {useForm} from 'react-hook-form';
import {LeadFormValues,leadSchema,PRIVACY_VERSION,PublicLeadRequest,submitLead} from '@/lib/lead-contract';
import {ApiError,messageOf} from '@/lib/api';

const QUEUE_KEY='havona_pending_lead';
function readQueue():PublicLeadRequest[]{try{const value=JSON.parse(localStorage.getItem(QUEUE_KEY)??'[]') as unknown;return Array.isArray(value)?value as PublicLeadRequest[]:[]}catch{return[]}}
function writeQueue(queue:PublicLeadRequest[]){if(queue.length)localStorage.setItem(QUEUE_KEY,JSON.stringify(queue));else localStorage.removeItem(QUEUE_KEY)}
function recoverable(error:unknown){return !(error instanceof ApiError)||error.status===429||error.status>=500}
function sourceFromLocation():PublicLeadRequest['source']{if(typeof window==='undefined')return 'organic';const params=new URLSearchParams(window.location.search);if(params.get('experiencia')==='henry')return 'henry-entry';if(params.get('utm_campaign'))return 'campaign';return document.referrer?'referral':'direct'}
function campaignFromLocation(){if(typeof window==='undefined')return undefined;return new URLSearchParams(window.location.search).get('utm_campaign')?.slice(0,100)||undefined}

export function LeadForm({landing,interest,compact=false}:{landing:string;interest:string;compact?:boolean}){const[status,setStatus]=useState<'idle'|'sending'|'queued'|'success'|'error'>('idle');const[result,setResult]=useState('');const{register,handleSubmit,formState:{errors},reset}=useForm<LeadFormValues>({resolver:zodResolver(leadSchema),defaultValues:{name:'',email:'',phone:'',city:'',message:'',consent:undefined,website:''}});
 useEffect(()=>{async function retry(){if(!navigator.onLine)return;const queue=readQueue();if(!queue.length)return;const pending:PublicLeadRequest[]=[];let delivered=false;for(const payload of queue){try{await submitLead(payload);delivered=true}catch(error){if(recoverable(error))pending.push(payload)}}writeQueue(pending);if(delivered&&!pending.length){setStatus('success');setResult('Recibimos su solicitud pendiente. Un consultor podrá revisarla.')}}window.addEventListener('online',retry);void retry();return()=>window.removeEventListener('online',retry)},[]);
 async function onSubmit(values:LeadFormValues){setStatus('sending');setResult('');const payload:PublicLeadRequest={submissionId:crypto.randomUUID(),name:values.name,phone:values.phone||undefined,email:values.email||undefined,city:values.city,source:sourceFromLocation(),campaign:campaignFromLocation(),landing,interest,message:values.message||undefined,consent:{accepted:true,privacyVersion:PRIVACY_VERSION},website:values.website};try{const response=await submitLead(payload);setStatus('success');setResult(response.message||'Recibimos su solicitud.');reset()}catch(error){if(recoverable(error)){writeQueue([...readQueue().filter(item=>item.submissionId!==payload.submissionId),payload]);setStatus('queued');setResult(navigator.onLine?`${messageOf(error)} Conservamos la información en este dispositivo para reintentar.`:'No hay conexión. Conservamos la información en este dispositivo y la enviaremos cuando vuelva la red.')}else{setStatus('error');setResult(messageOf(error))}}}
 if(status==='success')return <section id="consultoria" className="scroll-mt-32 rounded-[1.75rem] border border-emerald-200 bg-white p-8 shadow-card" aria-live="polite"><CheckCircle2 className="size-10 text-emerald-600"/><h2 className="mt-5 font-display text-2xl font-semibold text-brand-800">Solicitud recibida</h2><p className="mt-3 leading-7 text-slate-600">{result}</p><button type="button" onClick={()=>{setStatus('idle');setResult('')}} className="mt-6 text-sm font-semibold text-brand-700 underline decoration-blue-200 underline-offset-4">Enviar otra solicitud</button></section>;
 return <form id="consultoria" className={`scroll-mt-32 rounded-[1.75rem] border border-white bg-white shadow-card ${compact?'p-6 sm:p-7':'p-6 sm:p-9'}`} onSubmit={handleSubmit(onSubmit)} noValidate><div><p className="eyebrow">Contacto seguro</p><h2 className="mt-3 font-display text-3xl font-semibold text-brand-800">Conversemos sobre su objetivo</h2><p className="mt-3 leading-7 text-slate-600">Comparta sus datos y el contexto inicial. La confirmación depende de una respuesta real del sistema.</p></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Nombre completo" error={errors.name?.message}><input className={`field ${errors.name?'field-error':''}`} autoComplete="name" {...register('name')} /></Field><Field label="Ciudad" error={errors.city?.message}><input className={`field ${errors.city?'field-error':''}`} autoComplete="address-level2" {...register('city')} /></Field><Field label="Correo electrónico" error={errors.email?.message}><input type="email" className={`field ${errors.email?'field-error':''}`} autoComplete="email" {...register('email')} /></Field><Field label="Teléfono" error={errors.phone?.message}><input type="tel" inputMode="tel" className={`field ${errors.phone?'field-error':''}`} autoComplete="tel" {...register('phone')} /></Field><Field label="¿Qué le gustaría conversar?" error={errors.message?.message} wide><textarea rows={compact?3:4} className={`field min-h-28 py-3 ${errors.message?'field-error':''}`} {...register('message')} /></Field></div><div className="absolute left-[-9999px]" aria-hidden="true"><label>No completar<input tabIndex={-1} autoComplete="off" {...register('website')}/></label></div><div className="mt-6"><label className="flex cursor-pointer items-start gap-3 text-sm leading-6 text-slate-600"><input type="checkbox" className="mt-1 size-4 shrink-0 rounded border-slate-400 text-brand-700 focus:ring-brand-500" {...register('consent')}/><span>Autorizo de manera explícita el tratamiento de mis datos para atender esta solicitud, según la <Link href="/privacidad" target="_blank" className="font-semibold text-brand-700 underline underline-offset-2">política de privacidad</Link>.</span></label>{errors.consent&&<p className="mt-2 text-sm text-red-700" role="alert">{errors.consent.message}</p>}</div>{status==='queued'&&<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-900" role="status">{result}</p>}{status==='error'&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm leading-6 text-red-800" role="alert">{result}</p>}<button type="submit" disabled={status==='sending'} className="button-primary mt-7 w-full disabled:cursor-wait disabled:opacity-70">{status==='sending'?<><LoaderCircle className="size-4 animate-spin"/>Enviando</>:<>Enviar solicitud <Send className="size-4"/></>}</button></form>}

function Field({label,error,wide,children}:{label:string;error?:string;wide?:boolean;children:React.ReactElement}){const id=useId();return <label className={wide?'sm:col-span-2':''} htmlFor={id}><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{cloneElement(children,{'id':id,'aria-invalid':Boolean(error),'aria-describedby':error?`${id}-error`:undefined} as React.HTMLAttributes<HTMLElement>)}{error&&<span id={`${id}-error`} className="mt-1.5 block text-sm text-red-700" role="alert">{error}</span>}</label>}
