import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {LeadForm} from './lead-form';

describe('LeadForm',()=>{beforeEach(()=>{localStorage.clear();vi.restoreAllMocks();vi.stubGlobal('crypto',{randomUUID:()=> '7e3e371d-e3cb-4380-bd67-9acb5709cc72'})});afterEach(cleanup);
 it('asocia errores accesibles a campos y consentimiento',async()=>{render(<LeadForm landing="home" interest="consultoria"/>);fireEvent.click(screen.getByRole('button',{name:/enviar solicitud/i}));expect(await screen.findByText('Ingrese su nombre.')).toHaveAttribute('role','alert');const consentError=screen.getByText('Debe autorizar el tratamiento de sus datos.');const consent=screen.getByRole('checkbox');expect(consentError).toHaveAttribute('role','alert');expect(consent).toHaveAttribute('aria-invalid','true');expect(consent).toHaveAttribute('aria-describedby',consentError.id)});
 it('envía trazabilidad y consentimiento al endpoint público',async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{id:'prospect-1',status:'NEW'},message:'Solicitud recibida.'}),{status:201,headers:{'Content-Type':'application/json'}}));vi.stubGlobal('fetch',fetchMock);render(<LeadForm landing="pension" interest="pension"/>);fireEvent.change(screen.getByLabelText('Nombre completo'),{target:{value:'María Torres'}});fireEvent.change(screen.getByLabelText('Ciudad'),{target:{value:'Bogotá'}});fireEvent.change(screen.getByLabelText('Correo electrónico'),{target:{value:'maria@example.com'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:/enviar solicitud/i}));expect(await screen.findByText('Solicitud recibida.')).toBeInTheDocument();const[,init]=fetchMock.mock.calls[0] as [string,RequestInit];const payload=JSON.parse(init.body as string) as Record<string,unknown>;expect(payload).toMatchObject({submissionId:'7e3e371d-e3cb-4380-bd67-9acb5709cc72',landing:'pension',interest:'pension',name:'María Torres',consent:{accepted:true,privacyVersion:'2026-08-01'}})});
 it('conserva la captura cuando falla la red',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('Sin red')));render(<LeadForm landing="home" interest="consultoria"/>);fireEvent.change(screen.getByLabelText('Nombre completo'),{target:{value:'Ana López'}});fireEvent.change(screen.getByLabelText('Ciudad'),{target:{value:'Cali'}});fireEvent.change(screen.getByLabelText('Teléfono'),{target:{value:'+57 300 123 4567'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:/enviar solicitud/i}));await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent(/conservamos/i));expect(localStorage.getItem('havona_pending_lead')).toContain('7e3e371d-e3cb-4380-bd67-9acb5709cc72')});
 it('purga capturas locales después de 24 horas',async()=>{localStorage.setItem('havona_pending_lead',JSON.stringify([{payload:{submissionId:'old'},queuedAt:Date.now()-25*60*60*1000}]));render(<LeadForm landing="home" interest="consultoria"/>);await waitFor(()=>expect(localStorage.getItem('havona_pending_lead')).toBeNull())});
});
