'use client';
import Link from 'next/link';
import {AnimatePresence,motion} from 'motion/react';
import {Menu,X} from 'lucide-react';
import {usePathname} from 'next/navigation';
import {useState} from 'react';

const links=[{href:'/#soluciones',label:'Soluciones'},{href:'/#personas',label:'Personas'},{href:'/#empresas',label:'Empresas'},{href:'/privacidad',label:'Recursos'},{href:'/consultores',label:'Consultores'},{href:'/#consultoria',label:'Contacto'}];
export function PublicHeader(){const[open,setOpen]=useState(false);const path=usePathname();return <header className="fixed inset-x-0 top-0 z-50 px-3 pt-3 sm:px-6 sm:pt-5"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between rounded-2xl border border-white/70 bg-white/80 px-4 shadow-[0_12px_45px_rgba(7,26,51,.08)] backdrop-blur-xl sm:px-6"><Link href="/" className="font-display text-[15px] font-bold tracking-[.12em] text-brand-800 sm:text-lg" aria-label="HAVONA CAPITAL, inicio">HAVONA <span className="text-[#A17F3E]">CAPITAL</span></Link><nav className="hidden items-center gap-5 xl:flex" aria-label="Navegación pública">{links.map(link=><Link key={link.href} href={link.href} className="text-sm font-medium text-slate-600 transition hover:text-brand-700">{link.label}</Link>)}</nav><div className="ml-auto hidden items-center gap-3 md:flex xl:ml-0"><Link href="/login" className="px-3 py-2 text-sm font-semibold text-brand-800">Ingresar</Link><Link href="/#consultoria" className="button-primary min-h-11 px-5">Agenda una consultoría</Link></div><button type="button" onClick={()=>setOpen(v=>!v)} className="ml-2 grid size-11 place-items-center rounded-xl text-brand-800 hover:bg-brand-50 xl:hidden" aria-label={open?'Cerrar menú':'Abrir menú'} aria-expanded={open} aria-controls="mobile-navigation">{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.nav id="mobile-navigation" aria-label="Navegación móvil" className="mx-auto mt-2 grid max-w-[1440px] gap-1 rounded-2xl border border-white/70 bg-white p-3 shadow-xl xl:hidden" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{links.map(link=><Link key={link.href} href={link.href} onClick={()=>setOpen(false)} className="rounded-xl px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-brand-50" aria-current={path===link.href?'page':undefined}>{link.label}</Link>)}<div className="mt-2 grid grid-cols-2 gap-2 border-t pt-3 md:hidden"><Link href="/login" onClick={()=>setOpen(false)} className="button-secondary min-h-11">Ingresar</Link><Link href="/#consultoria" onClick={()=>setOpen(false)} className="button-primary min-h-11 px-3">Agendar</Link></div></motion.nav>}</AnimatePresence></header>}
