'use client';
import Link from 'next/link';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {ArrowUpRight,Menu,X} from 'lucide-react';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {BrandMark} from '../brand-mark';

const links=[{href:'/#soluciones',label:'Soluciones'},{href:'/#personas',label:'Personas'},{href:'/#empresas',label:'Empresas'},{href:'/privacidad',label:'Recursos'},{href:'/consultores',label:'Consultores'},{href:'/#consultoria',label:'Contacto'}];
export function PublicHeader(){const[open,setOpen]=useState(false),[compact,setCompact]=useState(false);const path=usePathname(),reduced=useReducedMotion();useEffect(()=>{const update=()=>setCompact(window.scrollY>36);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);useEffect(()=>setOpen(false),[path]);return <header className={`premium-header ${compact?'is-compact':''}`}><motion.div layout={!reduced} transition={{duration:.35,ease:[.22,1,.36,1]}} className="premium-nav"><BrandMark className="premium-wordmark"/><nav className="premium-links" aria-label="Navegación pública">{links.map(link=><Link key={link.href} href={link.href}>{link.label}</Link>)}</nav><div className="premium-actions"><Link href="/login" className="premium-login">Ingresar</Link><Link href="/#consultoria" className="premium-consult">Agenda una consultoría <ArrowUpRight/></Link></div><button type="button" onClick={()=>setOpen(value=>!value)} className="premium-menu" aria-label={open?'Cerrar menú':'Abrir menú'} aria-expanded={open} aria-controls="mobile-navigation">{open?<X/>:<Menu/>}</button></motion.div><AnimatePresence>{open&&<motion.nav id="mobile-navigation" aria-label="Navegación móvil" className="premium-mobile" initial={reduced?{opacity:0}:{opacity:0,y:-12,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-8,scale:.99}} transition={{duration:.25}}>{links.map((link,index)=><Link key={link.href} href={link.href} onClick={()=>setOpen(false)}><span>0{index+1}</span>{link.label}</Link>)}<div className="premium-mobile-actions"><Link href="/login">Ingresar</Link><Link href="/#consultoria">Agendar conversación <ArrowUpRight/></Link></div></motion.nav>}</AnimatePresence></header>}
