export const EMAIL_TEMPLATE_CATALOG = [
  ['prospecting.introduction', 'PROSPECTING'],
  ['prospecting.referral', 'PROSPECTING'],
  ['prospecting.inbound', 'PROSPECTING'],
  ['prospecting.corporate', 'PROSPECTING'],
  ['prospecting.reactivation', 'PROSPECTING'],
  ['meeting.confirmation', 'MEETINGS'],
  ['meeting.reminder', 'MEETINGS'],
  ['meeting.reschedule', 'MEETINGS'],
  ['meeting.cancellation', 'MEETINGS'],
  ['meeting.no_show_followup', 'MEETINGS'],
  ['proposal.thank_you', 'PROPOSAL'],
  ['proposal.information_request', 'PROPOSAL'],
  ['proposal.delivery', 'PROPOSAL'],
  ['proposal.followup', 'PROPOSAL'],
  ['proposal.thinking', 'PROPOSAL'],
  ['proposal.decision_pending', 'PROPOSAL'],
  ['onboarding.documents_request', 'ONBOARDING_ISSUANCE'],
  ['onboarding.missing_documents', 'ONBOARDING_ISSUANCE'],
  ['onboarding.application_received', 'ONBOARDING_ISSUANCE'],
  ['onboarding.status_update', 'ONBOARDING_ISSUANCE'],
  ['onboarding.policy_issued', 'ONBOARDING_ISSUANCE'],
  ['onboarding.welcome', 'ONBOARDING_ISSUANCE'],
  ['service.periodic_review', 'SERVICE_RETENTION'],
  ['service.data_update', 'SERVICE_RETENTION'],
  ['service.coverage_review', 'SERVICE_RETENTION'],
  ['service.anniversary', 'SERVICE_RETENTION'],
  ['service.post_sale', 'SERVICE_RETENTION'],
  ['payment.pending', 'PAYMENT_CONTINUITY'],
  ['payment.failed', 'PAYMENT_CONTINUITY'],
  ['payment.continuity_reminder', 'PAYMENT_CONTINUITY'],
  ['cancellation.retention', 'CANCELLATION_RECOVERY'],
  ['cancellation.confirmation', 'CANCELLATION_RECOVERY'],
] as const;

export const EMAIL_VARIABLES = [
  ['client.firstName', 'CLIENT', true, 'CRM Prospect.name'],
  ['client.fullName', 'CLIENT', true, 'CRM Prospect.name'],
  ['client.email', 'CLIENT', true, 'CRM Prospect.normalizedEmail'],
  ['consultant.firstName', 'CONSULTANT', true, 'User.name'],
  ['consultant.fullName', 'CONSULTANT', true, 'User.name'],
  ['consultant.email', 'CONSULTANT', true, 'User.email'],
  ['consultant.phone', 'CONSULTANT', false, 'EmailSignature.phone'],
  ['company.name', 'COMPANY', false, 'CRM Company.name'],
  ['appointment.date', 'CALENDAR', false, 'CalendarEventLink.startAt'],
  ['appointment.time', 'CALENDAR', false, 'CalendarEventLink.startAt'],
  ['appointment.timezone', 'CALENDAR', false, 'CalendarEventLink.timezone'],
  ['meeting.url', 'MEETING', false, 'Meeting join authorization'],
  ['opportunity.name', 'OPPORTUNITY', false, 'Opportunity.title'],
  ['product.name', 'KNOWLEDGE', false, 'Published authorized KnowledgeDocument'],
  ['system.companyName', 'SYSTEM', true, 'Corporate configuration'],
] as const;

export const variableRegistry = EMAIL_VARIABLES.map(
  ([key, type, requiredByDefault, dataSource]) => ({
    key,
    type,
    description: key,
    dataSource,
    requiredByDefault,
    formatter: 'TEXT',
    escapeStrategy: 'HTML_AND_HEADER',
  }),
);
