CREATE TABLE "users" ("id" UUID NOT NULL, "email" VARCHAR(254) NOT NULL, "name" VARCHAR(120) NOT NULL, "password_hash" TEXT NOT NULL, "is_active" BOOLEAN NOT NULL DEFAULT true, "failed_login_attempts" INTEGER NOT NULL DEFAULT 0, "locked_until" TIMESTAMP(3), "last_login_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE TABLE "roles" ("id" UUID NOT NULL, "name" VARCHAR(40) NOT NULL, "description" VARCHAR(240), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "roles_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "roles_name_key" ON "roles"("name");
CREATE TABLE "permissions" ("id" UUID NOT NULL, "key" VARCHAR(80) NOT NULL, "description" VARCHAR(240) NOT NULL, CONSTRAINT "permissions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "permissions_key_key" ON "permissions"("key");
CREATE TABLE "user_roles" ("user_id" UUID NOT NULL, "role_id" UUID NOT NULL, "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "user_roles_pkey" PRIMARY KEY ("user_id","role_id"));
CREATE TABLE "role_permissions" ("role_id" UUID NOT NULL, "permission_id" UUID NOT NULL, CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("role_id","permission_id"));
CREATE TABLE "sessions" ("id" UUID NOT NULL, "token_hash" CHAR(64) NOT NULL, "csrf_hash" CHAR(64) NOT NULL, "user_id" UUID NOT NULL, "expires_at" TIMESTAMP(3) NOT NULL, "revoked_at" TIMESTAMP(3), "ip_address" VARCHAR(64), "user_agent" VARCHAR(512), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "sessions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "sessions_token_hash_key" ON "sessions"("token_hash"); CREATE INDEX "sessions_user_id_expires_at_idx" ON "sessions"("user_id","expires_at");
CREATE TABLE "password_reset_tokens" ("id" UUID NOT NULL, "token_hash" CHAR(64) NOT NULL, "user_id" UUID NOT NULL, "expires_at" TIMESTAMP(3) NOT NULL, "used_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "password_reset_tokens_token_hash_key" ON "password_reset_tokens"("token_hash"); CREATE INDEX "password_reset_tokens_user_id_expires_at_idx" ON "password_reset_tokens"("user_id","expires_at");
CREATE TABLE "audit_logs" ("id" BIGSERIAL NOT NULL, "actor_user_id" UUID, "action" VARCHAR(80) NOT NULL, "resource" VARCHAR(80) NOT NULL, "resource_id" VARCHAR(80), "metadata" JSONB, "ip_address" VARCHAR(64), "user_agent" VARCHAR(512), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id"));
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs"("created_at"); CREATE INDEX "audit_logs_actor_user_id_idx" ON "audit_logs"("actor_user_id");
CREATE TABLE "system_settings" ("key" VARCHAR(100) NOT NULL, "value" JSONB NOT NULL, "description" VARCHAR(240), "is_public" BOOLEAN NOT NULL DEFAULT false, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "system_settings_pkey" PRIMARY KEY ("key"));
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
