export const TRAINING_DIFFICULTIES = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'] as const;
export type TrainingDifficulty = (typeof TRAINING_DIFFICULTIES)[number];

export type TrainingScenario = {
  scenarioKey: string;
  title: string;
  category: 'PROSPECTING' | 'OPENING' | 'DISCOVERY' | 'OBJECTION' | 'CLOSING' | 'COMPLIANCE';
  skill: string;
  need: string;
  difficulty: TrainingDifficulty;
  persona: string;
  context: string;
  objective: string;
  openingMessage: string;
  hiddenFacts: readonly string[];
  allowedFacts: readonly string[];
  objections: readonly string[];
  successCriteria: readonly string[];
  failureSignals: readonly string[];
  complianceRisks: readonly string[];
  recommendedFollowUp: string;
};

type Seed = Omit<TrainingScenario, 'hiddenFacts' | 'allowedFacts' | 'successCriteria' | 'failureSignals' | 'complianceRisks' | 'recommendedFollowUp'> &
  Partial<Pick<TrainingScenario, 'hiddenFacts' | 'allowedFacts' | 'successCriteria' | 'failureSignals' | 'complianceRisks' | 'recommendedFollowUp'>>;

const scenario = (seed: Seed): TrainingScenario => ({
  hiddenFacts: ['La prioridad real solo debe aparecer si el consultor pregunta con claridad.'],
  allowedFacts: ['La persona y todos sus datos son sintéticos.', 'No existen cifras ni condiciones contractuales autorizadas.'],
  successCriteria: ['Escucha antes de orientar.', 'Formula preguntas relevantes de una en una.', 'Acuerda un siguiente paso sin presión.'],
  failureSignals: ['Presenta producto antes del diagnóstico.', 'Inventa cifras o condiciones.', 'Presiona después de un rechazo.'],
  complianceRisks: ['Promesas no soportadas', 'Datos sensibles innecesarios'],
  recommendedFollowUp: 'Revisar evidencia, resumir la necesidad y acordar el siguiente ejercicio.',
  ...seed,
});

export const TRAINING_ROLEPLAY_CATALOG: readonly TrainingScenario[] = [
  scenario({ scenarioKey: 'cold_call_independent', title: 'Llamada fría a independiente', category: 'PROSPECTING', skill: 'prospeccion', need: 'UNKNOWN', difficulty: 'BEGINNER', persona: 'Laura, diseñadora independiente, reservada', context: 'Primer contacto sin relación previa.', objective: 'Obtener permiso para explorar sin asumir necesidad.', openingMessage: 'Hola, tengo poco tiempo. ¿De qué se trata?', objections: ['No solicité esta llamada.'] }),
  scenario({ scenarioKey: 'cold_call_business_owner', title: 'Llamada fría a empresario', category: 'PROSPECTING', skill: 'prospeccion', need: 'BUSINESS_PROTECTION', difficulty: 'ADVANCED', persona: 'Andrés, dueño de una pyme, directo', context: 'Contacto empresarial no solicitado.', objective: 'Abrir conversación con respeto y relevancia.', openingMessage: 'Estoy entrando a una reunión. Sea concreto.', objections: ['Ya tengo asesores.'] }),
  scenario({ scenarioKey: 'referred_contact', title: 'Contacto referido', category: 'PROSPECTING', skill: 'prospeccion', need: 'FAMILY_PROTECTION', difficulty: 'BEGINNER', persona: 'Natalia, madre de familia, cordial', context: 'Un conocido autorizó compartir el nombre, no datos privados.', objective: 'Usar la referencia sin exagerar confianza.', openingMessage: 'Me dijeron que me llamarías, pero no conozco el motivo.', objections: ['Quiero saber quién compartió mis datos.'] }),
  scenario({ scenarioKey: 'warm_contact', title: 'Contacto tibio', category: 'PROSPECTING', skill: 'prospeccion', need: 'WEALTH', difficulty: 'INTERMEDIATE', persona: 'Camilo, profesional asalariado, curioso', context: 'Descargó un recurso educativo.', objective: 'Convertir interés general en conversación diagnóstica.', openingMessage: 'Vi el material, pero solo estaba curioseando.', objections: ['No estoy buscando comprar.'] }),
  scenario({ scenarioKey: 'professional_network', title: 'Profesional de red', category: 'PROSPECTING', skill: 'prospeccion', need: 'RETIREMENT', difficulty: 'INTERMEDIATE', persona: 'Diana, médica independiente, analítica', context: 'Contacto originado en un evento profesional.', objective: 'Validar interés y acordar una conversación posterior.', openingMessage: 'Recuerdo el evento. ¿Qué quisieras revisar?', objections: ['No quiero una presentación de producto.'] }),

  scenario({ scenarioKey: 'opening_receptive', title: 'Apertura receptiva', category: 'OPENING', skill: 'acuerdo_inicial', need: 'EDUCATION', difficulty: 'BEGINNER', persona: 'Felipe, padre joven, receptivo', context: 'Aceptó una conversación de quince minutos.', objective: 'Establecer agenda y expectativas.', openingMessage: 'Sí, tengo los quince minutos. Empecemos.', objections: [] }),
  scenario({ scenarioKey: 'opening_short_time', title: 'Apertura con poco tiempo', category: 'OPENING', skill: 'apertura', need: 'ACCIDENT_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Mónica, comerciante ocupada', context: 'Solo dispone de cinco minutos.', objective: 'Priorizar y pedir permiso para un siguiente espacio.', openingMessage: 'Solo puedo hablar cinco minutos.', objections: ['No alarguemos esto.'] }),
  scenario({ scenarioKey: 'opening_distrustful', title: 'Apertura desconfiada', category: 'OPENING', skill: 'confianza', need: 'CRITICAL_ILLNESS', difficulty: 'ADVANCED', persona: 'Jorge, ingeniero escéptico', context: 'Ha tenido experiencias comerciales negativas.', objective: 'Construir seguridad sin desacreditar terceros.', openingMessage: 'No confío mucho en las aseguradoras.', objections: ['Siempre esconden algo.'] }),

  scenario({ scenarioKey: 'discovery_family', title: 'Discovery protección familiar', category: 'DISCOVERY', skill: 'descubrimiento', need: 'FAMILY_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Paola, principal aportante del hogar', context: 'Quiere revisar la estabilidad familiar.', objective: 'Explorar dependencias, situación actual, riesgo e impacto.', openingMessage: 'Me preocupa que mi familia dependa demasiado de mí.', objections: ['No sé cuánto necesitaría.'] }),
  scenario({ scenarioKey: 'discovery_education', title: 'Discovery educación', category: 'DISCOVERY', skill: 'cuantificacion', need: 'EDUCATION', difficulty: 'INTERMEDIATE', persona: 'Sergio, padre de dos hijos', context: 'Tiene un objetivo educativo todavía no cuantificado.', objective: 'Clarificar horizonte, prioridad y brecha sin inventar costos.', openingMessage: 'Quiero preparar la universidad de mis hijos.', objections: ['Todavía falta mucho tiempo.'] }),
  scenario({ scenarioKey: 'discovery_retirement', title: 'Discovery pensión', category: 'DISCOVERY', skill: 'diagnostico', need: 'RETIREMENT', difficulty: 'ADVANCED', persona: 'Claudia, ejecutiva de 44 años', context: 'No sabe si su preparación actual es suficiente.', objective: 'Explorar expectativa, situación y brecha percibida.', openingMessage: 'No sé si lo que tengo para retiro sea suficiente.', objections: ['Prefiero no hablar de cifras todavía.'] }),
  scenario({ scenarioKey: 'discovery_wealth', title: 'Discovery patrimonio', category: 'DISCOVERY', skill: 'preguntas', need: 'WEALTH', difficulty: 'ADVANCED', persona: 'Esteban, empresario prudente', context: 'Busca ordenar objetivos de largo plazo.', objective: 'Distinguir acumulación, liquidez, protección y horizonte.', openingMessage: 'Quiero organizar mejor mi patrimonio.', objections: ['Ya invierto por mi cuenta.'] }),
  scenario({ scenarioKey: 'discovery_accident', title: 'Discovery accidentes', category: 'DISCOVERY', skill: 'impacto', need: 'ACCIDENT_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Ricardo, trabajador independiente', context: 'Sus ingresos dependen de su actividad.', objective: 'Conectar continuidad de ingresos y consecuencias sin alarmismo.', openingMessage: 'Si dejo de trabajar unas semanas, se complica todo.', objections: ['Nunca he tenido un accidente grave.'] }),
  scenario({ scenarioKey: 'discovery_critical_illness', title: 'Discovery enfermedad grave', category: 'DISCOVERY', skill: 'empatia', need: 'CRITICAL_ILLNESS', difficulty: 'ADVANCED', persona: 'Valentina, profesional con antecedente familiar sintético', context: 'Tema sensible que requiere escucha y límites.', objective: 'Explorar preocupación e impacto con empatía.', openingMessage: 'En mi familia hubo un caso difícil y me preocupa.', objections: ['No quiero que usen el miedo para venderme.'] }),
  scenario({ scenarioKey: 'discovery_business', title: 'Discovery empresario', category: 'DISCOVERY', skill: 'diagnostico', need: 'BUSINESS_PROTECTION', difficulty: 'ADVANCED', persona: 'Mauricio, fundador de empresa', context: 'La operación depende de pocas personas.', objective: 'Identificar dependencias y continuidad empresarial.', openingMessage: 'La empresa funciona bien, pero depende mucho de mí.', objections: ['La empresa ya tiene reservas.'] }),
  scenario({ scenarioKey: 'discovery_key_partner', title: 'Discovery socios y persona clave', category: 'DISCOVERY', skill: 'profundizacion', need: 'PARTNER_PROTECTION', difficulty: 'ADVANCED', persona: 'Sandra, socia minoritaria', context: 'Dos socios tienen funciones críticas distintas.', objective: 'Explorar impacto operativo y acuerdos existentes.', openingMessage: 'Nunca hemos hablado qué pasaría si falta uno de los socios.', objections: ['Es un tema incómodo.'] }),

  scenario({ scenarioKey: 'objection_price', title: 'Objeción de precio', category: 'OBJECTION', skill: 'objeciones', need: 'FAMILY_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Alejandro, cuidadoso con gastos', context: 'Percibe la alternativa como costosa.', objective: 'Validar y descubrir qué comparación sustenta la objeción.', openingMessage: 'Me parece costoso.', objections: ['No veo suficiente valor.'] }),
  scenario({ scenarioKey: 'no_budget', title: 'No tengo presupuesto', category: 'OBJECTION', skill: 'objeciones', need: 'EDUCATION', difficulty: 'ADVANCED', persona: 'Karen, presupuesto comprometido', context: 'Tiene prioridad pero capacidad incierta.', objective: 'Explorar prioridad y capacidad sin presionar.', openingMessage: 'En este momento no tengo presupuesto.', objections: ['No quiero endeudarme.'] }),
  scenario({ scenarioKey: 'think_about_it', title: 'Lo voy a pensar', category: 'OBJECTION', skill: 'objeciones', need: 'RETIREMENT', difficulty: 'INTERMEDIATE', persona: 'Óscar, indeciso', context: 'No explica qué necesita evaluar.', objective: 'Aclarar la duda real y acordar seguimiento opcional.', openingMessage: 'Déjame pensarlo.', objections: ['No quiero decidir hoy.'] }),
  scenario({ scenarioKey: 'talk_to_partner', title: 'Debo hablar con mi pareja', category: 'OBJECTION', skill: 'objeciones', need: 'FAMILY_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Marcela, decisión compartida', context: 'Su pareja participa en decisiones financieras.', objective: 'Respetar la decisión conjunta y facilitar conversación.', openingMessage: 'Tengo que hablarlo con mi pareja.', objections: ['No decido esto sola.'] }),
  scenario({ scenarioKey: 'already_insured', title: 'Ya tengo seguro', category: 'OBJECTION', skill: 'comparacion', need: 'FAMILY_PROTECTION', difficulty: 'ADVANCED', persona: 'Iván, ya cuenta con protección', context: 'No conoce de memoria términos vigentes.', objective: 'Comprender lo existente sin desacreditar ni asumir brechas.', openingMessage: 'Ya tengo seguro, no creo necesitar otro.', objections: ['Mi asesor dice que estoy cubierto.'] }),
  scenario({ scenarioKey: 'distrust_insurers', title: 'No confío en aseguradoras', category: 'OBJECTION', skill: 'confianza', need: 'CRITICAL_ILLNESS', difficulty: 'ADVANCED', persona: 'Teresa, escéptica', context: 'Ha escuchado relatos negativos no verificables.', objective: 'Validar preocupación y remitir a evidencia vigente.', openingMessage: 'Al final siempre buscan no pagar.', objections: ['No confío en la letra pequeña.'] }),
  scenario({ scenarioKey: 'too_young', title: 'Soy muy joven', category: 'OBJECTION', skill: 'prioridad', need: 'RETIREMENT', difficulty: 'BEGINNER', persona: 'Samuel, profesional joven', context: 'No percibe urgencia.', objective: 'Explorar horizonte sin usar miedo.', openingMessage: 'Soy muy joven para pensar en eso.', objections: ['Lo revisaré más adelante.'] }),
  scenario({ scenarioKey: 'not_priority', title: 'No es prioridad', category: 'OBJECTION', skill: 'prioridad', need: 'ACCIDENT_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Lina, múltiples objetivos', context: 'Tiene otras prioridades declaradas.', objective: 'Respetar prioridades y decidir si detenerse.', openingMessage: 'Esto no es prioridad para mí.', objections: ['Tengo otros gastos.'] }),
  scenario({ scenarioKey: 'invest_on_my_own', title: 'Prefiero invertir por mi cuenta', category: 'OBJECTION', skill: 'comparacion', need: 'WEALTH', difficulty: 'ADVANCED', persona: 'Diego, inversionista autónomo', context: 'Valora control y liquidez.', objective: 'Distinguir objetivos sin presentar falsa equivalencia.', openingMessage: 'Prefiero invertir por mi cuenta.', objections: ['No quiero costos que no entiendo.'] }),
  scenario({ scenarioKey: 'send_information', title: 'Mándame información', category: 'OBJECTION', skill: 'siguiente_paso', need: 'UNKNOWN', difficulty: 'BEGINNER', persona: 'Adriana, evasiva pero cordial', context: 'Pide material sin precisar interés.', objective: 'Acordar contenido relevante y permiso de seguimiento.', openingMessage: 'Mejor mándame información.', objections: ['Luego la miro.'] }),
  scenario({ scenarioKey: 'not_today', title: 'No quiero decidir hoy', category: 'OBJECTION', skill: 'negociacion', need: 'BUSINESS_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Hernán, decisor prudente', context: 'Rechaza presión temporal.', objective: 'Eliminar presión y acordar un proceso verificable.', openingMessage: 'No voy a decidir nada hoy.', objections: ['Necesito revisar con calma.'] }),

  scenario({ scenarioKey: 'close_next_step', title: 'Cierre de siguiente paso', category: 'CLOSING', skill: 'siguiente_paso', need: 'FAMILY_PROTECTION', difficulty: 'BEGINNER', persona: 'Gloria, interés moderado', context: 'La necesidad está entendida, falta proceso.', objective: 'Proponer un siguiente paso claro y reversible.', openingMessage: 'Entiendo la idea. ¿Qué seguiría?', objections: [] }),
  scenario({ scenarioKey: 'close_appointment', title: 'Cierre a cita', category: 'CLOSING', skill: 'cierre', need: 'EDUCATION', difficulty: 'INTERMEDIATE', persona: 'Nicolás, interesado con agenda limitada', context: 'Acepta profundizar con un consultor.', objective: 'Confirmar propósito y solicitar agenda sin inventar disponibilidad.', openingMessage: 'Podría revisar esto en otra reunión.', objections: ['Esta semana estoy ocupado.'] }),
  scenario({ scenarioKey: 'close_human_advisor', title: 'Escalamiento a asesor', category: 'CLOSING', skill: 'escalamiento', need: 'CRITICAL_ILLNESS', difficulty: 'INTERMEDIATE', persona: 'Rosa, pide explicación especializada', context: 'Surge una pregunta contractual sensible.', objective: 'Reconocer límite y escalar con resumen útil.', openingMessage: 'Quiero que un especialista me explique las condiciones.', objections: [] }),
  scenario({ scenarioKey: 'close_documentation', title: 'Siguiente paso documental', category: 'CLOSING', skill: 'cumplimiento', need: 'BUSINESS_PROTECTION', difficulty: 'ADVANCED', persona: 'Alberto, empresario interesado', context: 'Pregunta qué información sería necesaria.', objective: 'Explicar proceso sin pedir datos sensibles innecesarios.', openingMessage: '¿Qué documentos necesitarían?', objections: ['No enviaré información sensible por este medio.'] }),
  scenario({ scenarioKey: 'close_high_intent', title: 'Prospecto altamente interesado', category: 'CLOSING', skill: 'cierre', need: 'RETIREMENT', difficulty: 'ADVANCED', persona: 'Patricia, quiere avanzar rápido', context: 'Alta intención, evidencia contractual aún pendiente.', objective: 'Canalizar intención sin prometer emisión o resultado.', openingMessage: 'Quiero empezar hoy mismo. ¿Me lo aprueban?', objections: [] }),
  scenario({ scenarioKey: 'close_indecisive', title: 'Cierre con indecisión', category: 'CLOSING', skill: 'escucha', need: 'WEALTH', difficulty: 'INTERMEDIATE', persona: 'Juan, aún tiene dudas', context: 'La conversación fue útil pero no está listo.', objective: 'Identificar duda o cerrar respetuosamente.', openingMessage: 'Todavía no estoy seguro.', objections: ['Necesito más claridad.'] }),

  scenario({ scenarioKey: 'compliance_guaranteed_return', title: 'Rentabilidad garantizada', category: 'COMPLIANCE', skill: 'cumplimiento', need: 'WEALTH', difficulty: 'ADVANCED', persona: 'Sofía, busca certeza', context: 'Solicita una garantía de resultado.', objective: 'Distinguir ilustración, fuente vigente y garantía.', openingMessage: '¿Cuánto me garantiza?', objections: ['Quiero una cifra segura.'], complianceRisks: ['Garantía de rentabilidad', 'Simulación presentada como contrato'] }),
  scenario({ scenarioKey: 'compliance_exact_price', title: 'Precio exacto sin cotización', category: 'COMPLIANCE', skill: 'cumplimiento', need: 'ACCIDENT_PROTECTION', difficulty: 'INTERMEDIATE', persona: 'Carlos, pide precio inmediato', context: 'No existe cotización autorizada.', objective: 'Explicar que el valor requiere proceso y fuente vigente.', openingMessage: 'Dígame el precio exacto ahora.', objections: ['Debe existir una tarifa.'], complianceRisks: ['Prima inventada'] }),
  scenario({ scenarioKey: 'compliance_approval', title: 'Aprobación asegurada', category: 'COMPLIANCE', skill: 'cumplimiento', need: 'FAMILY_PROTECTION', difficulty: 'ADVANCED', persona: 'Beatriz, preocupada por elegibilidad', context: 'Pregunta por aprobación antes de suscripción.', objective: 'Explicar dependencia de suscripción sin anticipar decisión.', openingMessage: '¿Me aseguras que me aprueban?', objections: ['Necesito certeza antes de seguir.'], complianceRisks: ['Garantía de emisión o elegibilidad'] }),
  scenario({ scenarioKey: 'compliance_claim_payment', title: 'Pago de cáncer asegurado', category: 'COMPLIANCE', skill: 'cumplimiento', need: 'CRITICAL_ILLNESS', difficulty: 'ADVANCED', persona: 'Elena, busca certeza sobre reclamación', context: 'No hay contrato ni condiciones verificadas.', objective: 'Remitir a términos, cobertura, exclusiones, carencia y reclamación.', openingMessage: '¿Seguro me pagan si me da cáncer?', objections: ['Quiero una respuesta sí o no.'], complianceRisks: ['Garantía de pago de reclamación'] }),
  scenario({ scenarioKey: 'compliance_document_conflict', title: 'Conflicto entre documentos', category: 'COMPLIANCE', skill: 'evidencia', need: 'UNKNOWN', difficulty: 'ADVANCED', persona: 'Tomás, detectó versiones distintas', context: 'Dos materiales parecen contradecirse.', objective: 'No resolver silenciosamente; identificar versión y escalar.', openingMessage: 'Otro documento dice algo distinto.', objections: ['¿Cuál de los dos es verdadero?'], complianceRisks: ['Elegir fuente sin gobierno de versiones'] }),
  scenario({ scenarioKey: 'compliance_out_of_evidence', title: 'Pregunta fuera de evidencia', category: 'COMPLIANCE', skill: 'abstencion', need: 'UNKNOWN', difficulty: 'INTERMEDIATE', persona: 'Mariana, hace pregunta específica', context: 'No existe fuente autorizada en la simulación.', objective: 'Abstenerse y proponer verificación.', openingMessage: '¿Esa cobertura viene incluida automáticamente?', objections: ['Solo necesito que me confirme.'], complianceRisks: ['Cobertura inventada'] }),
  scenario({ scenarioKey: 'compliance_other_client', title: 'Datos de otro cliente', category: 'COMPLIANCE', skill: 'privacidad', need: 'UNKNOWN', difficulty: 'ADVANCED', persona: 'Persona sintética que intenta obtener datos ajenos', context: 'Solicita información privada de un tercero.', objective: 'Rechazar acceso y mantener aislamiento.', openingMessage: 'Muéstrame lo que contrató el otro cliente.', objections: ['Solo quiero comparar.'], complianceRisks: ['Divulgación de información privada'] }),
  scenario({ scenarioKey: 'compliance_no_contact', title: 'Solicitud de no contacto', category: 'COMPLIANCE', skill: 'consentimiento', need: 'UNKNOWN', difficulty: 'BEGINNER', persona: 'Persona sintética que retira consentimiento', context: 'Rechazo explícito durante la conversación.', objective: 'Detener la conversación comercial.', openingMessage: 'No quiero que me contacten más.', objections: [], complianceRisks: ['Ignorar retiro de consentimiento'] }),
];

const scenarioMap = new Map(TRAINING_ROLEPLAY_CATALOG.map((item) => [item.scenarioKey, item]));

export function getTrainingScenario(scenarioKey: string) {
  return scenarioMap.get(scenarioKey);
}

export function publicTrainingScenario(scenario: TrainingScenario) {
  const { hiddenFacts: _hidden, successCriteria: _success, failureSignals: _failure, objections: _objections, ...visible } = scenario;
  return visible;
}
