export type PublicPage={slug:string;title:string;shortTitle:string;description:string;eyebrow:string;problem:string;context:string;solution:string;benefits:string[];interest:string};
export const publicPages:PublicPage[]=[
 {slug:'pension',title:'Proyecte su retiro con una ruta clara',shortTitle:'Pensión',description:'Consultoría para ordenar objetivos, horizonte y decisiones relacionadas con su retiro.',eyebrow:'Personas · Retiro',problem:'Pensar en el retiro suele posponerse porque existen muchas variables y pocas respuestas simples.',context:'Su edad, dinámica familiar, expectativas y capacidad actual hacen parte de una conversación que debe ser personal.',solution:'Una consultoría inicial permite organizar el contexto, identificar prioridades y definir próximos pasos sin promesas ni cifras genéricas.',benefits:['Claridad sobre sus objetivos de retiro.','Lectura integral de su contexto personal.','Ruta de trabajo acompañada por un consultor.'],interest:'pension'},
 {slug:'educacion',title:'Prepare hoy los proyectos educativos del mañana',shortTitle:'Educación',description:'Planeación patrimonial orientada a los proyectos educativos de su familia.',eyebrow:'Personas · Educación',problem:'Los proyectos educativos requieren anticipación y compiten con otras prioridades familiares.',context:'El horizonte, las personas involucradas y las metas particulares determinan cómo debe abordarse la planeación.',solution:'Organizamos una conversación consultiva para comprender su proyecto y explorar una ruta coherente con su realidad.',benefits:['Objetivo educativo definido con claridad.','Planeación conectada con su contexto familiar.','Acompañamiento para establecer siguientes pasos.'],interest:'educacion'},
 {slug:'patrimonio',title:'Construya patrimonio con intención y perspectiva',shortTitle:'Patrimonio',description:'Consultoría para estructurar objetivos de acumulación de capital y patrimonio.',eyebrow:'Personas · Patrimonio',problem:'Acumular recursos sin una visión conectada puede alejar sus decisiones de las metas que realmente importan.',context:'El patrimonio se construye alrededor de propósitos, horizontes y responsabilidades diferentes para cada persona.',solution:'Partimos de sus objetivos para ordenar prioridades y abrir una ruta consultiva responsable.',benefits:['Objetivos patrimoniales organizados.','Visión de corto y largo plazo.','Acompañamiento sin afirmaciones financieras no sustentadas.'],interest:'patrimonio'},
 {slug:'proteccion',title:'Proteja la continuidad de quienes más importan',shortTitle:'Protección familiar',description:'Consultoría inicial para identificar necesidades de protección familiar.',eyebrow:'Personas · Protección',problem:'Un evento inesperado puede alterar la estabilidad y los planes de una familia.',context:'Las responsabilidades económicas, dependientes y proyectos compartidos definen necesidades distintas.',solution:'Revisamos su contexto para identificar conversaciones prioritarias de protección, siempre con información clara.',benefits:['Lectura inicial de responsabilidades familiares.','Prioridades de protección identificadas.','Acompañamiento humano y trazable.'],interest:'proteccion'},
 {slug:'accidentes',title:'Anticipe el impacto de los imprevistos',shortTitle:'Accidentes personales',description:'Orientación inicial sobre protección frente a accidentes personales.',eyebrow:'Personas · Imprevistos',problem:'Los accidentes pueden afectar ingresos, rutinas y estabilidad sin dar tiempo para reorganizarse.',context:'La ocupación, las responsabilidades y el entorno personal influyen en la protección que conviene evaluar.',solution:'Una conversación inicial ayuda a ordenar riesgos y determinar si es necesario profundizar con un consultor.',benefits:['Riesgos personales puestos en contexto.','Necesidades iniciales identificadas.','Proceso respetuoso de sus datos y decisiones.'],interest:'accidentes'},
 {slug:'empresarios',title:'Proteja la continuidad de su empresa',shortTitle:'Empresarios',description:'Consultoría de protección empresarial para organizaciones y sus líderes.',eyebrow:'Empresas · Continuidad',problem:'La operación puede depender de personas, relaciones y decisiones cuya ausencia genera un impacto relevante.',context:'Cada organización tiene una estructura, responsabilidades y puntos críticos particulares.',solution:'Iniciamos un diagnóstico consultivo para comprender la empresa y priorizar riesgos de continuidad.',benefits:['Contexto empresarial comprendido.','Riesgos prioritarios identificados.','Siguiente conversación asignada con trazabilidad.'],interest:'empresarios'},
 {slug:'socios',title:'Fortalezca la protección entre socios',shortTitle:'Socios',description:'Acompañamiento inicial para explorar necesidades de protección societaria.',eyebrow:'Empresas · Socios',problem:'Los cambios inesperados en una sociedad pueden comprometer continuidad, control y relaciones construidas durante años.',context:'La composición accionaria, los acuerdos y los roles requieren una lectura cuidadosa, no una fórmula genérica.',solution:'Recopilamos el contexto inicial y orientamos la conversación hacia las necesidades reales de los socios.',benefits:['Estructura societaria puesta en contexto.','Puntos críticos para profundizar.','Registro seguro de la solicitud y consentimiento.'],interest:'socios'},
 {slug:'socio-unico',title:'Reduzca la dependencia crítica del socio único',shortTitle:'Socio único',description:'Consultoría para comprender riesgos de continuidad en empresas lideradas por un socio único.',eyebrow:'Empresas · Socio único',problem:'Cuando dirección, conocimiento y relaciones se concentran en una sola persona, la continuidad puede ser vulnerable.',context:'La empresa, la familia y el equipo necesitan ser considerados dentro de una misma conversación.',solution:'Exploramos dependencias y prioridades para dirigir una consultoría empresarial pertinente.',benefits:['Dependencias críticas identificadas.','Visión conjunta de empresa y familia.','Ruta consultiva inicial con trazabilidad.'],interest:'socio-unico'},
 {slug:'consultores',title:'Construya una carrera consultiva con propósito',shortTitle:'Consultores',description:'Conozca el proceso inicial para conversar sobre oportunidades como consultor de HAVONA CAPITAL GROUP.',eyebrow:'Talento · Consultores',problem:'Una carrera consultiva exige propósito, método, aprendizaje y una organización con visión de largo plazo.',context:'Buscamos comprender su trayectoria, ciudad e interés antes de abrir una conversación sobre el modelo consultivo.',solution:'Registre su interés para que el equipo autorizado evalúe el contexto y determine el siguiente paso.',benefits:['Solicitud registrada de forma segura.','Contexto profesional desde el primer contacto.','Proceso inicial trazable y sin promesas automáticas.'],interest:'consultores'},
];
export const publicPageMap=new Map(publicPages.map(page=>[page.slug,page]));
